version: '3'
services:
  db:
    image: mysql:5.7
    container_name: manager-db
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root12345
      MYSQL_DATABASE: master_db
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - 3306:3306
  api:
    build: ./manager
    image: manager-api
    container_name: manager-api
    tty: true
    volumes:
      - ./manager:/manager_api:delegated
    ports:
      - 3000:3000
    depends_on:
      - db
  agent:
    build: ./agent
    image: agent-api
    container_name: agent-api
    tty: true
    volumes:
      - ./agent:/agent-api:delegated
    ports:
      - 4567:80
    depends_on:
      - db
volumes:
  bundle:
    driver: local
