default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: master_db
  host: manager-db
  username: testuser
  password: testpass

production:
  <<: *default
  database: master_db
  host: <%= Rails.application.credentials.database[:host] %>
  username: <%= Rails.application.credentials.database[:user] %>
  password: <%= Rails.application.credentials.database[:pass] %>
