default: &default
  adapter: mysql2
  encoding: utf8

development:
  <<: *default
  database: master_db
  host: manager-db
  username: testuser
  password: testpass

production:
  <<: *default
  database: master_db
  host: <%= ENV.fetch('DB_HOST') %>
  username: <%= ENV.fetch('DB_USER') %>
  password: <%= ENV.fetch('DB_PASS') %>
